# This is a basic workflow to help you get started with Actions

name: Zip Mod Folders

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'HeartAttack/**'
      - 'HumorousDeath/**'
      - 'InterruptReminder/**'
      - 'LibFramePool-1.0/**'
      - 'TalkingHeadShut/**'
      - 'ThreatTrack/**'
      - 'ZoomerWoW/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          folders=("HeartAttack" "HumorousDeath" "InterruptReminder" "LibFramePool-1.0" "TalkingHeadShut" "ThreatTrack" "ZoomerWoW")
          for folder in "${folders[@]}"; do
            files=()
            cd "${folder}"
            version=$(head -n2 *.toc | tail -n1 | awk '{print $3}')
            zip_name="${folder}_v${version}.zip"
            for item in "."/*; do
              if [[ "$item" != "./_misc" && "$item" != "./*.zip" ]]; then
                files+=("$item")
              fi
            done
            zip -r "$zip_name" "${files[@]}"
            echo "Created zip file $zip_name"
            mv "$zip_name" ../.github
            cd ..
          done
      - name: Push ZIPs to repo
        run: |
          cd .github
          ls -la
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Committed ZIP folders"
          
