# This is a basic workflow to help you get started with Actions

name: Zip Mod Folders

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'HeartAttack/**'
      - 'HumorousDeath/**'
      - 'InterruptReminder/**'
      - 'LibFramePool-1.0/**'
      - 'TalkingHeadShut/**'
      - 'ThreatTrack/**'
      - 'ZoomerWoW/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.filter.outputs.test }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            test:
              - 'test_folder/**'
            

  test1:
    needs: build
    if: ${{ needs.build.outputs.test == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello!"
            
      
          
